### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by dummyvx** [warren-bank/crx-2Embed#1]
updated to 2embed.to and click to copy for the pop-up

**Comment by warren-bank** [comment]
at the time you opened this issue, I can confirm that the domain _2embed.ru_ was offline and performing a temporary 302 redirect to _2embed.to_

at this moment, when I finally got around to updating this repo.. both domains are alive and well;
so.. the update that I just made will allow the userscript to work on either domain.

if one goes down.. it's good to know that there's (at least one) working mirror.
thanks for letting me know, and posting this issue.
